public class Main {
    static void main(String[] args)
    /*before we start coding, we need to write such as public class main { static void main (string[] args)*/ {
        System.out.println("first Java program");
        System.out.print("hello world$$$$$\n");
        System.out.print("programing java cafe!!\n");
        System.out.print("system.out.print we use to output \n");
        System.out.print("System.out.println we use for newline coding\n");
        System.out.print("home \n");
        System.out.println("book!!!!");
        System.out.println("<<<<<<System control date>>>>>\n");
        int year = 2026;
        int month = 4;
        int day = 4;
        System.out.println("This year is\t" + year);
        System.out.println("The month is\t" + month);
        System.out.println("The day is\t" + day);
        System.out.println("\n");
        System.out.println("<<System control money and people>>>");
        double money = 20000.56;
        int girl = 1;
        int Man = 1;
        System.out.println("Student\t" + girl);
        System.out.println("CEO\t" + Man);
        System.out.println("Money\t$" + money);
        double good = 50;
        double average = 100;
        double bad = 203;
        double total;
        total = (good + average + bad / 3);
        System.out.println(total);
        boolean teacher = false;
        boolean student = false;
        boolean teaching = true;
        // we use boolean : for true or false of value
        if(teacher) {
            System.out.println("you are not Management!!");
        } else {
            System.out.println("you are Management!!");
        }
        if(student) {
            System.out.println("you are not Student!!");
        }
        //  Right now we use string : we use string to store litters such as name with double ""
        // My topic such as : car , name , food , color , email;
        String name = "leap heng";
        String car = "GTR R34";
        String color = "blue";
        String food = "rice";
        String email = "hengleap2323@gmail.com";
        System.out.println("My name is " + name + "\n");
        System.out.println("your car is " + car + "Nisan\n");
        System.out.println("I think you are obsessed with color :" + color + "\n");
        System.out.println("My favorite food is : " + food + "\n");
        boolean forsale = true;
        if (forsale) {
            System.out.println(" this  car not for sale:" + car + "\n");
        } else {
            System.out.println(" this  car  for sale:" + car + "\n");
        }
    }






}
